// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://paw-meet-backend.onrender.com' | (string & {});
};

/**
 * Serializer para gestionar asistencias.
 */
export type Attendance = {
    readonly id: number;
    readonly meeting: number;
    readonly user: string;
    readonly user_email: string;
    readonly user_name: string;
    /**
     * Mascotas que trae el usuario a este encuentro
     */
    pets?: Array<string>;
    readonly pets_details: Array<Pet>;
    status?: AttendanceStatusEnum;
    /**
     * Notas adicionales del asistente
     */
    notes?: string;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Serializer para gestionar asistencias.
 */
export type AttendanceRequest = {
    /**
     * Mascotas que trae el usuario a este encuentro
     */
    pets?: Array<string>;
    status?: AttendanceStatusEnum;
    /**
     * Notas adicionales del asistente
     */
    notes?: string;
};

/**
 * * `confirmed` - Confirmado
 * * `cancelled` - Cancelado
 * * `attended` - Asistió
 * * `no_show` - No asistió
 */
export type AttendanceStatusEnum = 'confirmed' | 'cancelled' | 'attended' | 'no_show';

export type BlankEnum = '';

/**
 * Serializador sencillo para las categorías.
 * Normalmente, los usuarios solo las leen (GET). La creación suele ser de admin.
 */
export type CategoriaPublicacion = {
    readonly id: number;
    nombre: string;
};

/**
 * Serializador sencillo para las categorías.
 * Normalmente, los usuarios solo las leen (GET). La creación suele ser de admin.
 */
export type CategoriaPublicacionRequest = {
    nombre: string;
};

/**
 * Cambio de contraseña autenticado.
 * Requiere la contraseña actual como verificación.
 */
export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
    new_password_confirm: string;
};

/**
 * Serializer para el modelo City.
 */
export type City = {
    readonly id: number;
    name: string;
    province?: string;
};

/**
 * Serializer para el modelo City.
 */
export type CityRequest = {
    name: string;
    province?: string;
};

export type ClaimAdminResponse = {
    readonly detail: string;
};

/**
 * Serializador detallado de un foro.
 * Incluye la lista de publicaciones que contiene.
 * Se usa para ver un foro concreto y para crearlo.
 */
export type ForoDetail = {
    readonly id: number;
    titulo: string;
    tipo_foro: string;
    usuario: UserPublic;
    readonly publicaciones: Array<PublicacionList>;
    encuentro?: number | null;
};

/**
 * Serializador detallado de un foro.
 * Incluye la lista de publicaciones que contiene.
 * Se usa para ver un foro concreto y para crearlo.
 */
export type ForoDetailRequest = {
    titulo: string;
    tipo_foro: string;
    encuentro?: number | null;
};

/**
 * Serializador para listar los foros disponibles.
 * Muestra información general y el creador.
 */
export type ForoList = {
    readonly id: number;
    titulo: string;
    tipo_foro: string;
    usuario: UserPublic;
    readonly total_publicaciones: string;
    encuentro?: number | null;
};

/**
 * Serializer detallado para encuentros (incluye información de asistentes).
 */
export type MeetingDetail = {
    readonly id: number;
    title: string;
    description: string;
    /**
     * Fecha del encuentro
     */
    date: string;
    /**
     * Hora de inicio
     */
    start_time: string;
    /**
     * Hora de finalización
     */
    end_time: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location: string;
    /**
     * Latitud para geolocalización
     */
    location_lat?: string | null;
    /**
     * Longitud para geolocalización
     */
    location_lng?: string | null;
    city: City;
    readonly creator: string;
    readonly creator_email: string;
    readonly creator_name: string;
    pets?: Array<string>;
    readonly pets_details: Array<Pet>;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
    readonly confirmed_attendees_count: string;
    readonly available_spots: number;
    status: StatusD0dEnum;
    readonly attendees: Array<Attendance>;
    readonly is_creator: string;
    readonly user_attendance: string;
    readonly can_join: string;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Serializer detallado para encuentros (incluye información de asistentes).
 */
export type MeetingDetailRequest = {
    title: string;
    description: string;
    /**
     * Fecha del encuentro
     */
    date: string;
    /**
     * Hora de inicio
     */
    start_time: string;
    /**
     * Hora de finalización
     */
    end_time: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location: string;
    /**
     * Latitud para geolocalización
     */
    location_lat?: string | null;
    /**
     * Longitud para geolocalización
     */
    location_lng?: string | null;
    pets?: Array<string>;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
};

/**
 * Serializer para listados de encuentros.
 */
export type MeetingList = {
    readonly id: number;
    title: string;
    description: string;
    /**
     * Fecha del encuentro
     */
    date: string;
    /**
     * Hora de inicio
     */
    start_time: string;
    /**
     * Hora de finalización
     */
    end_time: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location: string;
    city: number;
    readonly city_name: string;
    creator: string;
    readonly creator_name: string;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
    readonly confirmed_attendees: string;
    readonly available_spots: number;
    status?: StatusD0dEnum;
    readonly is_attending: string;
    readonly created_at: string;
};

export type PaginatedMeetingDetailList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MeetingDetail>;
};

export type PaginatedPublicacionDetailList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PublicacionDetail>;
};

export type PaginatedUserProfileList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserProfile>;
};

/**
 * Serializer para gestionar asistencias.
 */
export type PatchedAttendanceRequest = {
    /**
     * Mascotas que trae el usuario a este encuentro
     */
    pets?: Array<string>;
    status?: AttendanceStatusEnum;
    /**
     * Notas adicionales del asistente
     */
    notes?: string;
};

/**
 * Serializador sencillo para las categorías.
 * Normalmente, los usuarios solo las leen (GET). La creación suele ser de admin.
 */
export type PatchedCategoriaPublicacionRequest = {
    nombre?: string;
};

/**
 * Serializer para el modelo City.
 */
export type PatchedCityRequest = {
    name?: string;
    province?: string;
};

/**
 * Serializador detallado de un foro.
 * Incluye la lista de publicaciones que contiene.
 * Se usa para ver un foro concreto y para crearlo.
 */
export type PatchedForoDetailRequest = {
    titulo?: string;
    tipo_foro?: string;
    encuentro?: number | null;
};

/**
 * Serializer detallado para encuentros (incluye información de asistentes).
 */
export type PatchedMeetingDetailRequest = {
    title?: string;
    description?: string;
    /**
     * Fecha del encuentro
     */
    date?: string;
    /**
     * Hora de inicio
     */
    start_time?: string;
    /**
     * Hora de finalización
     */
    end_time?: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location?: string;
    /**
     * Latitud para geolocalización
     */
    location_lat?: string | null;
    /**
     * Longitud para geolocalización
     */
    location_lng?: string | null;
    pets?: Array<string>;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
};

/**
 * Serializer completo de mascota para el dueño autenticado.
 * Lectura + escritura. El campo 'owner' se inyecta desde la view,
 * nunca lo envía el cliente (evita asignación arbitraria de propiedad).
 */
export type PatchedPetRequest = {
    name?: string;
    /**
     * Tipo de mascota registrada.
     */
    pet_type?: string;
    /**
     * Especie libre (rellenar solo si tipo es 'Otro').
     */
    species?: string;
    /**
     * Raza de la mascota.
     */
    breed?: string;
    /**
     * Tamaño aproximado. Especialmente relevante para perros.
     *
     * * `small` - Pequeño (< 10kg)
     * * `medium` - Mediano (10-25kg)
     * * `large` - Grande (> 25kg)
     */
    size?: SizeEnum | BlankEnum;
    /**
     * Fecha de nacimiento. Permite calcular edad en la API.
     */
    birth_date?: string | null;
    /**
     * Descripción de la mascota: carácter, gustos, etc.
     */
    bio?: string;
    /**
     * Foto de la mascota.
     */
    avatar?: Blob | File | null;
    /**
     * Permite 'archivar' mascotas sin eliminarlas (fallecidas, etc.).
     */
    is_active?: boolean;
};

/**
 * Serializer completo de tipo de mascota para los administradores.
 * Lectura + Escritura.
 */
export type PatchedPetTypeRequest = {
    id?: string;
    nombre?: string;
    codigo?: string;
};

/**
 * Serializador para ver el detalle de una publicación (al hacer clic en ella).
 * Aquí sí enviamos el texto completo.
 * También se usa para CREAR (POST) o ACTUALIZAR (PUT/PATCH).
 */
export type PatchedPublicacionDetailRequest = {
    titulo?: string;
    texto?: string;
    foto?: Blob | File | null;
};

/**
 * Perfil privado: solo accesible por el propio usuario autenticado.
 * Permite editar datos de perfil. El email se puede actualizar
 * con validación de unicidad. El password NO se cambia desde aquí
 * (hay endpoint dedicado para eso).
 */
export type PatchedUserProfileRequest = {
    email?: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username?: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: Blob | File | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
    /**
     * Teléfono de contacto opcional
     */
    phone?: string;
};

/**
 * Serializer completo de mascota para el dueño autenticado.
 * Lectura + escritura. El campo 'owner' se inyecta desde la view,
 * nunca lo envía el cliente (evita asignación arbitraria de propiedad).
 */
export type Pet = {
    readonly id: string;
    name: string;
    /**
     * Tipo de mascota registrada.
     */
    pet_type: string;
    /**
     * Especie libre (rellenar solo si tipo es 'Otro').
     */
    species?: string;
    /**
     * Raza de la mascota.
     */
    breed?: string;
    /**
     * Tamaño aproximado. Especialmente relevante para perros.
     *
     * * `small` - Pequeño (< 10kg)
     * * `medium` - Mediano (10-25kg)
     * * `large` - Grande (> 25kg)
     */
    size?: SizeEnum | BlankEnum;
    /**
     * Fecha de nacimiento. Permite calcular edad en la API.
     */
    birth_date?: string | null;
    /**
     * Descripción de la mascota: carácter, gustos, etc.
     */
    bio?: string;
    /**
     * Foto de la mascota.
     */
    avatar?: string | null;
    /**
     * Permite 'archivar' mascotas sin eliminarlas (fallecidas, etc.).
     */
    is_active?: boolean;
    /**
     * Calcula la edad en años si birth_date está definida.
     */
    readonly age_years: number | null;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Vista reducida de mascota para mostrar en perfiles públicos
 * y en los encuentros. No expone owner_id directamente.
 */
export type PetPublic = {
    name: string;
    /**
     * Tipo de mascota registrada.
     */
    pet_type: string;
    /**
     * Especie libre (rellenar solo si tipo es 'Otro').
     */
    species?: string;
    /**
     * Raza de la mascota.
     */
    breed?: string;
    /**
     * Tamaño aproximado. Especialmente relevante para perros.
     *
     * * `small` - Pequeño (< 10kg)
     * * `medium` - Mediano (10-25kg)
     * * `large` - Grande (> 25kg)
     */
    size?: SizeEnum | BlankEnum;
    /**
     * Foto de la mascota.
     */
    avatar?: string | null;
};

/**
 * Vista reducida de mascota para mostrar en perfiles públicos
 * y en los encuentros. No expone owner_id directamente.
 */
export type PetPublicRequest = {
    name: string;
    /**
     * Tipo de mascota registrada.
     */
    pet_type: string;
    /**
     * Especie libre (rellenar solo si tipo es 'Otro').
     */
    species?: string;
    /**
     * Raza de la mascota.
     */
    breed?: string;
    /**
     * Tamaño aproximado. Especialmente relevante para perros.
     *
     * * `small` - Pequeño (< 10kg)
     * * `medium` - Mediano (10-25kg)
     * * `large` - Grande (> 25kg)
     */
    size?: SizeEnum | BlankEnum;
    /**
     * Foto de la mascota.
     */
    avatar?: Blob | File | null;
};

/**
 * Serializer completo de mascota para el dueño autenticado.
 * Lectura + escritura. El campo 'owner' se inyecta desde la view,
 * nunca lo envía el cliente (evita asignación arbitraria de propiedad).
 */
export type PetRequest = {
    name: string;
    /**
     * Tipo de mascota registrada.
     */
    pet_type: string;
    /**
     * Especie libre (rellenar solo si tipo es 'Otro').
     */
    species?: string;
    /**
     * Raza de la mascota.
     */
    breed?: string;
    /**
     * Tamaño aproximado. Especialmente relevante para perros.
     *
     * * `small` - Pequeño (< 10kg)
     * * `medium` - Mediano (10-25kg)
     * * `large` - Grande (> 25kg)
     */
    size?: SizeEnum | BlankEnum;
    /**
     * Fecha de nacimiento. Permite calcular edad en la API.
     */
    birth_date?: string | null;
    /**
     * Descripción de la mascota: carácter, gustos, etc.
     */
    bio?: string;
    /**
     * Foto de la mascota.
     */
    avatar?: Blob | File | null;
    /**
     * Permite 'archivar' mascotas sin eliminarlas (fallecidas, etc.).
     */
    is_active?: boolean;
};

/**
 * Serializer completo de tipo de mascota para los administradores.
 * Lectura + Escritura.
 */
export type PetType = {
    id?: string;
    nombre?: string;
    codigo?: string;
};

/**
 * Serializer completo de tipo de mascota para los administradores.
 * Lectura + Escritura.
 */
export type PetTypeRequest = {
    id?: string;
    nombre?: string;
    codigo?: string;
};

/**
 * Serializador para ver el detalle de una publicación (al hacer clic en ella).
 * Aquí sí enviamos el texto completo.
 * También se usa para CREAR (POST) o ACTUALIZAR (PUT/PATCH).
 */
export type PublicacionDetail = {
    readonly id: number;
    titulo: string;
    texto: string;
    foto?: string | null;
    readonly uploaded_at: string;
    readonly likes: number;
    usuario_detail: UserPublic;
    categoria_detail: CategoriaPublicacion;
};

/**
 * Serializador para ver el detalle de una publicación (al hacer clic en ella).
 * Aquí sí enviamos el texto completo.
 * También se usa para CREAR (POST) o ACTUALIZAR (PUT/PATCH).
 */
export type PublicacionDetailRequest = {
    titulo: string;
    texto: string;
    foto?: Blob | File | null;
};

/**
 * Serializador para listar publicaciones (ej: en el feed o dentro de un foro).
 * Anidamos la categoría para que el frontend no tenga que hacer peticiones extra,
 * y mostramos un resumen del usuario autor.
 */
export type PublicacionList = {
    readonly id: number;
    titulo: string;
    usuario: UserPublic;
    categoria: CategoriaPublicacion;
    foto?: string | null;
    readonly uploaded_at: string;
    likes?: number;
};

/**
 * Serializador para listar publicaciones (ej: en el feed o dentro de un foro).
 * Anidamos la categoría para que el frontend no tenga que hacer peticiones extra,
 * y mostramos un resumen del usuario autor.
 */
export type PublicacionListRequest = {
    titulo: string;
    foto?: Blob | File | null;
    likes?: number;
};

/**
 * * `user` - Usuario
 * * `admin` - Administrador
 */
export type RoleEnum = 'user' | 'admin';

/**
 * * `small` - Pequeño (< 10kg)
 * * `medium` - Mediano (10-25kg)
 * * `large` - Grande (> 25kg)
 */
export type SizeEnum = 'small' | 'medium' | 'large';

/**
 * * `scheduled` - Programado
 * * `ongoing` - En curso
 * * `completed` - Completado
 * * `cancelled` - Cancelado
 */
export type StatusD0dEnum = 'scheduled' | 'ongoing' | 'completed' | 'cancelled';

/**
 * Perfil privado: solo accesible por el propio usuario autenticado.
 * Permite editar datos de perfil. El email se puede actualizar
 * con validación de unicidad. El password NO se cambia desde aquí
 * (hay endpoint dedicado para eso).
 */
export type UserProfile = {
    readonly id: string;
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    readonly full_name: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: string | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
    /**
     * Teléfono de contacto opcional
     */
    phone?: string;
    role: RoleEnum;
    /**
     * Activo
     *
     * Indica si el usuario debe ser tratado como activo. Desmarque esta opción en lugar de borrar la cuenta.
     */
    readonly is_active: boolean;
    /**
     * Fecha de alta
     */
    readonly date_joined: string;
    /**
     * Último inicio de sesión
     */
    readonly last_login: string | null;
    readonly pets: Array<Pet>;
};

/**
 * Perfil privado: solo accesible por el propio usuario autenticado.
 * Permite editar datos de perfil. El email se puede actualizar
 * con validación de unicidad. El password NO se cambia desde aquí
 * (hay endpoint dedicado para eso).
 */
export type UserProfileRequest = {
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: Blob | File | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
    /**
     * Teléfono de contacto opcional
     */
    phone?: string;
};

/**
 * Perfil público de un usuario. Lo ven otros usuarios de la app.
 * Expone solo información no sensible.
 */
export type UserPublic = {
    id?: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    readonly full_name: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: string | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
    readonly pets: Array<PetPublic>;
};

/**
 * Perfil público de un usuario. Lo ven otros usuarios de la app.
 * Expone solo información no sensible.
 */
export type UserPublicRequest = {
    id?: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: Blob | File | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
};

/**
 * Registro de nuevo usuario.
 * - Valida que password y password_confirm coincidan.
 * - Aplica los validadores de contraseña de Django (settings.AUTH_PASSWORD_VALIDATORS).
 * - NO devuelve el password en la respuesta.
 */
export type UserRegistration = {
    readonly id: string;
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
};

/**
 * Registro de nuevo usuario.
 * - Valida que password y password_confirm coincidan.
 * - Aplica los validadores de contraseña de Django (settings.AUTH_PASSWORD_VALIDATORS).
 * - NO devuelve el password en la respuesta.
 */
export type UserRegistrationRequest = {
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
};

/**
 * Serializer para gestionar asistencias.
 */
export type AttendanceWritable = {
    /**
     * Mascotas que trae el usuario a este encuentro
     */
    pets?: Array<string>;
    status?: AttendanceStatusEnum;
    /**
     * Notas adicionales del asistente
     */
    notes?: string;
};

/**
 * Serializer para gestionar asistencias.
 */
export type AttendanceRequestWritable = {
    /**
     * Mascotas que trae el usuario a este encuentro
     */
    pets?: Array<string>;
    pet_ids?: Array<string>;
    status?: AttendanceStatusEnum;
    /**
     * Notas adicionales del asistente
     */
    notes?: string;
};

/**
 * Serializador sencillo para las categorías.
 * Normalmente, los usuarios solo las leen (GET). La creación suele ser de admin.
 */
export type CategoriaPublicacionWritable = {
    nombre: string;
};

/**
 * Serializer para el modelo City.
 */
export type CityWritable = {
    name: string;
    province?: string;
};

/**
 * Serializador detallado de un foro.
 * Incluye la lista de publicaciones que contiene.
 * Se usa para ver un foro concreto y para crearlo.
 */
export type ForoDetailWritable = {
    titulo: string;
    tipo_foro: string;
    encuentro?: number | null;
};

/**
 * Serializador para listar los foros disponibles.
 * Muestra información general y el creador.
 */
export type ForoListWritable = {
    titulo: string;
    tipo_foro: string;
    encuentro?: number | null;
};

/**
 * Serializer detallado para encuentros (incluye información de asistentes).
 */
export type MeetingDetailWritable = {
    title: string;
    description: string;
    /**
     * Fecha del encuentro
     */
    date: string;
    /**
     * Hora de inicio
     */
    start_time: string;
    /**
     * Hora de finalización
     */
    end_time: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location: string;
    /**
     * Latitud para geolocalización
     */
    location_lat?: string | null;
    /**
     * Longitud para geolocalización
     */
    location_lng?: string | null;
    pets?: Array<string>;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
};

/**
 * Serializer detallado para encuentros (incluye información de asistentes).
 */
export type MeetingDetailRequestWritable = {
    title: string;
    description: string;
    /**
     * Fecha del encuentro
     */
    date: string;
    /**
     * Hora de inicio
     */
    start_time: string;
    /**
     * Hora de finalización
     */
    end_time: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location: string;
    /**
     * Latitud para geolocalización
     */
    location_lat?: string | null;
    /**
     * Longitud para geolocalización
     */
    location_lng?: string | null;
    city_id: number;
    pets?: Array<string>;
    pet_ids?: Array<string>;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
};

/**
 * Serializer para listados de encuentros.
 */
export type MeetingListWritable = {
    title: string;
    description: string;
    /**
     * Fecha del encuentro
     */
    date: string;
    /**
     * Hora de inicio
     */
    start_time: string;
    /**
     * Hora de finalización
     */
    end_time: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location: string;
    city: number;
    creator: string;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
    status?: StatusD0dEnum;
};

export type PaginatedMeetingDetailListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MeetingDetailWritable>;
};

export type PaginatedPublicacionDetailListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PublicacionDetailWritable>;
};

export type PaginatedUserProfileListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserProfileWritable>;
};

/**
 * Serializer para gestionar asistencias.
 */
export type PatchedAttendanceRequestWritable = {
    /**
     * Mascotas que trae el usuario a este encuentro
     */
    pets?: Array<string>;
    pet_ids?: Array<string>;
    status?: AttendanceStatusEnum;
    /**
     * Notas adicionales del asistente
     */
    notes?: string;
};

/**
 * Serializer detallado para encuentros (incluye información de asistentes).
 */
export type PatchedMeetingDetailRequestWritable = {
    title?: string;
    description?: string;
    /**
     * Fecha del encuentro
     */
    date?: string;
    /**
     * Hora de inicio
     */
    start_time?: string;
    /**
     * Hora de finalización
     */
    end_time?: string;
    /**
     * Dirección o punto de encuentro específico
     */
    location?: string;
    /**
     * Latitud para geolocalización
     */
    location_lat?: string | null;
    /**
     * Longitud para geolocalización
     */
    location_lng?: string | null;
    city_id?: number;
    pets?: Array<string>;
    pet_ids?: Array<string>;
    /**
     * Número máximo de participantes (incluye al creador)
     */
    max_participants?: number;
};

/**
 * Serializador para ver el detalle de una publicación (al hacer clic en ella).
 * Aquí sí enviamos el texto completo.
 * También se usa para CREAR (POST) o ACTUALIZAR (PUT/PATCH).
 */
export type PatchedPublicacionDetailRequestWritable = {
    titulo?: string;
    texto?: string;
    foto?: Blob | File | null;
    categoria_id?: number | null;
    foro_id?: number;
};

/**
 * Serializer completo de mascota para el dueño autenticado.
 * Lectura + escritura. El campo 'owner' se inyecta desde la view,
 * nunca lo envía el cliente (evita asignación arbitraria de propiedad).
 */
export type PetWritable = {
    name: string;
    /**
     * Tipo de mascota registrada.
     */
    pet_type: string;
    /**
     * Especie libre (rellenar solo si tipo es 'Otro').
     */
    species?: string;
    /**
     * Raza de la mascota.
     */
    breed?: string;
    /**
     * Tamaño aproximado. Especialmente relevante para perros.
     *
     * * `small` - Pequeño (< 10kg)
     * * `medium` - Mediano (10-25kg)
     * * `large` - Grande (> 25kg)
     */
    size?: SizeEnum | BlankEnum;
    /**
     * Fecha de nacimiento. Permite calcular edad en la API.
     */
    birth_date?: string | null;
    /**
     * Descripción de la mascota: carácter, gustos, etc.
     */
    bio?: string;
    /**
     * Foto de la mascota.
     */
    avatar?: string | null;
    /**
     * Permite 'archivar' mascotas sin eliminarlas (fallecidas, etc.).
     */
    is_active?: boolean;
};

/**
 * Serializador para ver el detalle de una publicación (al hacer clic en ella).
 * Aquí sí enviamos el texto completo.
 * También se usa para CREAR (POST) o ACTUALIZAR (PUT/PATCH).
 */
export type PublicacionDetailWritable = {
    titulo: string;
    texto: string;
    foto?: string | null;
};

/**
 * Serializador para ver el detalle de una publicación (al hacer clic en ella).
 * Aquí sí enviamos el texto completo.
 * También se usa para CREAR (POST) o ACTUALIZAR (PUT/PATCH).
 */
export type PublicacionDetailRequestWritable = {
    titulo: string;
    texto: string;
    foto?: Blob | File | null;
    categoria_id?: number | null;
    foro_id: number;
};

/**
 * Serializador para listar publicaciones (ej: en el feed o dentro de un foro).
 * Anidamos la categoría para que el frontend no tenga que hacer peticiones extra,
 * y mostramos un resumen del usuario autor.
 */
export type PublicacionListWritable = {
    titulo: string;
    foto?: string | null;
    likes?: number;
};

/**
 * Perfil privado: solo accesible por el propio usuario autenticado.
 * Permite editar datos de perfil. El email se puede actualizar
 * con validación de unicidad. El password NO se cambia desde aquí
 * (hay endpoint dedicado para eso).
 */
export type UserProfileWritable = {
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: string | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
    /**
     * Teléfono de contacto opcional
     */
    phone?: string;
};

/**
 * Perfil público de un usuario. Lo ven otros usuarios de la app.
 * Expone solo información no sensible.
 */
export type UserPublicWritable = {
    id?: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Descripción personal del usuario. Máx. 500 caracteres recomendados.
     */
    bio?: string;
    /**
     * Foto de perfil del usuario.
     */
    avatar?: string | null;
    /**
     * Ciudad o zona del usuario para filtros de encuentros.
     */
    ciudad?: string;
};

/**
 * Registro de nuevo usuario.
 * - Valida que password y password_confirm coincidan.
 * - Aplica los validadores de contraseña de Django (settings.AUTH_PASSWORD_VALIDATORS).
 * - NO devuelve el password en la respuesta.
 */
export type UserRegistrationWritable = {
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
};

/**
 * Registro de nuevo usuario.
 * - Valida que password y password_confirm coincidan.
 * - Aplica los validadores de contraseña de Django (settings.AUTH_PASSWORD_VALIDATORS).
 * - NO devuelve el password en la respuesta.
 */
export type UserRegistrationRequestWritable = {
    email: string;
    /**
     * Nombre de usuario
     *
     * Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
     */
    username: string;
    /**
     * Nombre
     */
    first_name?: string;
    /**
     * Apellidos
     */
    last_name?: string;
    password: string;
    password_confirm: string;
};

export type AdminCreateCreateData = {
    body: UserRegistrationRequestWritable;
    path?: never;
    query?: never;
    url: '/api/admin/create/';
};

export type AdminCreateCreateResponses = {
    201: UserRegistration;
};

export type AdminCreateCreateResponse = AdminCreateCreateResponses[keyof AdminCreateCreateResponses];

export type AdminEncuentrosListListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Un número de página dentro del conjunto de resultados paginado.
         */
        page?: number;
        /**
         * Número de resultados a devolver por página.
         */
        page_size?: number;
    };
    url: '/api/admin/encuentros/list/';
};

export type AdminEncuentrosListListResponses = {
    200: PaginatedMeetingDetailList;
};

export type AdminEncuentrosListListResponse = AdminEncuentrosListListResponses[keyof AdminEncuentrosListListResponses];

export type AdminLoginCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/login/';
};

export type AdminLoginCreateErrors = {
    403: ClaimAdminResponse;
};

export type AdminLoginCreateError = AdminLoginCreateErrors[keyof AdminLoginCreateErrors];

export type AdminLoginCreateResponses = {
    200: ClaimAdminResponse;
};

export type AdminLoginCreateResponse = AdminLoginCreateResponses[keyof AdminLoginCreateResponses];

export type AdminSocialPublicacionesListListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Un número de página dentro del conjunto de resultados paginado.
         */
        page?: number;
        /**
         * Número de resultados a devolver por página.
         */
        page_size?: number;
    };
    url: '/api/admin/social/publicaciones/list/';
};

export type AdminSocialPublicacionesListListResponses = {
    200: PaginatedPublicacionDetailList;
};

export type AdminSocialPublicacionesListListResponse = AdminSocialPublicacionesListListResponses[keyof AdminSocialPublicacionesListListResponses];

export type AdminUsersDeleteDestroyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email del usuario a eliminar
         */
        email: string;
    };
    url: '/api/admin/users/delete/';
};

export type AdminUsersDeleteDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AdminUsersDeleteDestroyResponse = AdminUsersDeleteDestroyResponses[keyof AdminUsersDeleteDestroyResponses];

export type AdminUsersListListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Un número de página dentro del conjunto de resultados paginado.
         */
        page?: number;
        /**
         * Número de resultados a devolver por página.
         */
        page_size?: number;
    };
    url: '/api/admin/users/list/';
};

export type AdminUsersListListResponses = {
    200: PaginatedUserProfileList;
};

export type AdminUsersListListResponse = AdminUsersListListResponses[keyof AdminUsersListListResponses];

export type AttendancesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attendances/';
};

export type AttendancesListResponses = {
    200: Array<Attendance>;
};

export type AttendancesListResponse = AttendancesListResponses[keyof AttendancesListResponses];

export type AttendancesDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attendances/{id}/';
};

export type AttendancesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AttendancesDestroyResponse = AttendancesDestroyResponses[keyof AttendancesDestroyResponses];

export type AttendancesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attendances/{id}/';
};

export type AttendancesRetrieveResponses = {
    200: Attendance;
};

export type AttendancesRetrieveResponse = AttendancesRetrieveResponses[keyof AttendancesRetrieveResponses];

export type AttendancesPartialUpdateData = {
    body?: PatchedAttendanceRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attendances/{id}/';
};

export type AttendancesPartialUpdateResponses = {
    200: Attendance;
};

export type AttendancesPartialUpdateResponse = AttendancesPartialUpdateResponses[keyof AttendancesPartialUpdateResponses];

export type AttendancesUpdateData = {
    body?: AttendanceRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attendances/{id}/';
};

export type AttendancesUpdateResponses = {
    200: Attendance;
};

export type AttendancesUpdateResponse = AttendancesUpdateResponses[keyof AttendancesUpdateResponses];

export type CitiesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Un término de búsqueda.
         */
        search?: string;
    };
    url: '/api/cities/';
};

export type CitiesListResponses = {
    200: Array<City>;
};

export type CitiesListResponse = CitiesListResponses[keyof CitiesListResponses];

export type CitiesCreateData = {
    body: CityRequest;
    path?: never;
    query?: never;
    url: '/api/cities/';
};

export type CitiesCreateResponses = {
    201: City;
};

export type CitiesCreateResponse = CitiesCreateResponses[keyof CitiesCreateResponses];

export type CitiesDestroyData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este Ciudad.
         */
        id: number;
    };
    query?: never;
    url: '/api/cities/{id}/';
};

export type CitiesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CitiesDestroyResponse = CitiesDestroyResponses[keyof CitiesDestroyResponses];

export type CitiesRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este Ciudad.
         */
        id: number;
    };
    query?: never;
    url: '/api/cities/{id}/';
};

export type CitiesRetrieveResponses = {
    200: City;
};

export type CitiesRetrieveResponse = CitiesRetrieveResponses[keyof CitiesRetrieveResponses];

export type CitiesPartialUpdateData = {
    body?: PatchedCityRequest;
    path: {
        /**
         * Un valor de entero único que identifique este Ciudad.
         */
        id: number;
    };
    query?: never;
    url: '/api/cities/{id}/';
};

export type CitiesPartialUpdateResponses = {
    200: City;
};

export type CitiesPartialUpdateResponse = CitiesPartialUpdateResponses[keyof CitiesPartialUpdateResponses];

export type CitiesUpdateData = {
    body: CityRequest;
    path: {
        /**
         * Un valor de entero único que identifique este Ciudad.
         */
        id: number;
    };
    query?: never;
    url: '/api/cities/{id}/';
};

export type CitiesUpdateResponses = {
    200: City;
};

export type CitiesUpdateResponse = CitiesUpdateResponses[keyof CitiesUpdateResponses];

export type MeetingsListData = {
    body?: never;
    path?: never;
    query?: {
        city?: number;
        date?: string;
        /**
         * Qué campo usar para ordenar los resultados.
         */
        ordering?: string;
        /**
         * Un término de búsqueda.
         */
        search?: string;
        /**
         * * `scheduled` - Programado
         * * `ongoing` - En curso
         * * `completed` - Completado
         * * `cancelled` - Cancelado
         */
        status?: 'cancelled' | 'completed' | 'ongoing' | 'scheduled';
    };
    url: '/api/meetings/';
};

export type MeetingsListResponses = {
    200: Array<MeetingList>;
};

export type MeetingsListResponse = MeetingsListResponses[keyof MeetingsListResponses];

export type MeetingsCreateData = {
    body: MeetingDetailRequestWritable;
    path?: never;
    query?: never;
    url: '/api/meetings/';
};

export type MeetingsCreateResponses = {
    201: MeetingDetail;
};

export type MeetingsCreateResponse = MeetingsCreateResponses[keyof MeetingsCreateResponses];

export type MeetingsDestroyData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/';
};

export type MeetingsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type MeetingsDestroyResponse = MeetingsDestroyResponses[keyof MeetingsDestroyResponses];

export type MeetingsRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/';
};

export type MeetingsRetrieveResponses = {
    200: MeetingDetail;
};

export type MeetingsRetrieveResponse = MeetingsRetrieveResponses[keyof MeetingsRetrieveResponses];

export type MeetingsPartialUpdateData = {
    body?: PatchedMeetingDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/';
};

export type MeetingsPartialUpdateResponses = {
    200: MeetingDetail;
};

export type MeetingsPartialUpdateResponse = MeetingsPartialUpdateResponses[keyof MeetingsPartialUpdateResponses];

export type MeetingsUpdateData = {
    body: MeetingDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/';
};

export type MeetingsUpdateResponses = {
    200: MeetingDetail;
};

export type MeetingsUpdateResponse = MeetingsUpdateResponses[keyof MeetingsUpdateResponses];

export type MeetingsAttendeesRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/attendees/';
};

export type MeetingsAttendeesRetrieveResponses = {
    200: MeetingDetail;
};

export type MeetingsAttendeesRetrieveResponse = MeetingsAttendeesRetrieveResponses[keyof MeetingsAttendeesRetrieveResponses];

export type MeetingsCancelCreateData = {
    body: MeetingDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/cancel/';
};

export type MeetingsCancelCreateResponses = {
    200: MeetingDetail;
};

export type MeetingsCancelCreateResponse = MeetingsCancelCreateResponses[keyof MeetingsCancelCreateResponses];

export type MeetingsJoinCreateData = {
    body: MeetingDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/join/';
};

export type MeetingsJoinCreateResponses = {
    200: MeetingDetail;
};

export type MeetingsJoinCreateResponse = MeetingsJoinCreateResponses[keyof MeetingsJoinCreateResponses];

export type MeetingsLeaveCreateData = {
    body: MeetingDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este Encuentro.
         */
        id: number;
    };
    query?: never;
    url: '/api/meetings/{id}/leave/';
};

export type MeetingsLeaveCreateResponses = {
    200: MeetingDetail;
};

export type MeetingsLeaveCreateResponse = MeetingsLeaveCreateResponses[keyof MeetingsLeaveCreateResponses];

export type MeetingsMyMeetingsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meetings/my_meetings/';
};

export type MeetingsMyMeetingsRetrieveResponses = {
    200: MeetingDetail;
};

export type MeetingsMyMeetingsRetrieveResponse = MeetingsMyMeetingsRetrieveResponses[keyof MeetingsMyMeetingsRetrieveResponses];

export type MeetingsNearbyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meetings/nearby/';
};

export type MeetingsNearbyRetrieveResponses = {
    200: MeetingDetail;
};

export type MeetingsNearbyRetrieveResponse = MeetingsNearbyRetrieveResponses[keyof MeetingsNearbyRetrieveResponses];

export type PettypesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pettypes/';
};

export type PettypesListResponses = {
    200: Array<PetType>;
};

export type PettypesListResponse = PettypesListResponses[keyof PettypesListResponses];

export type PettypesCreateData = {
    body?: PetTypeRequest;
    path?: never;
    query?: never;
    url: '/api/pettypes/';
};

export type PettypesCreateResponses = {
    201: PetType;
};

export type PettypesCreateResponse = PettypesCreateResponses[keyof PettypesCreateResponses];

export type PettypesDestroyData = {
    body?: never;
    path: {
        /**
         * Un Cadena UUID que identifique este pet_type.
         */
        id: string;
    };
    query?: never;
    url: '/api/pettypes/{id}/';
};

export type PettypesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type PettypesDestroyResponse = PettypesDestroyResponses[keyof PettypesDestroyResponses];

export type PettypesRetrieveData = {
    body?: never;
    path: {
        /**
         * Un Cadena UUID que identifique este pet_type.
         */
        id: string;
    };
    query?: never;
    url: '/api/pettypes/{id}/';
};

export type PettypesRetrieveResponses = {
    200: PetType;
};

export type PettypesRetrieveResponse = PettypesRetrieveResponses[keyof PettypesRetrieveResponses];

export type PettypesPartialUpdateData = {
    body?: PatchedPetTypeRequest;
    path: {
        /**
         * Un Cadena UUID que identifique este pet_type.
         */
        id: string;
    };
    query?: never;
    url: '/api/pettypes/{id}/';
};

export type PettypesPartialUpdateResponses = {
    200: PetType;
};

export type PettypesPartialUpdateResponse = PettypesPartialUpdateResponses[keyof PettypesPartialUpdateResponses];

export type PettypesUpdateData = {
    body?: PetTypeRequest;
    path: {
        /**
         * Un Cadena UUID que identifique este pet_type.
         */
        id: string;
    };
    query?: never;
    url: '/api/pettypes/{id}/';
};

export type PettypesUpdateResponses = {
    200: PetType;
};

export type PettypesUpdateResponse = PettypesUpdateResponses[keyof PettypesUpdateResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'en' | 'es';
    };
    url: '/api/schema';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type SocialCategoriasListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/social/categorias/';
};

export type SocialCategoriasListResponses = {
    200: Array<CategoriaPublicacion>;
};

export type SocialCategoriasListResponse = SocialCategoriasListResponses[keyof SocialCategoriasListResponses];

export type SocialCategoriasCreateData = {
    body: CategoriaPublicacionRequest;
    path?: never;
    query?: never;
    url: '/api/social/categorias/';
};

export type SocialCategoriasCreateResponses = {
    201: CategoriaPublicacion;
};

export type SocialCategoriasCreateResponse = SocialCategoriasCreateResponses[keyof SocialCategoriasCreateResponses];

export type SocialCategoriasDestroyData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este categoria publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/categorias/{id}/';
};

export type SocialCategoriasDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SocialCategoriasDestroyResponse = SocialCategoriasDestroyResponses[keyof SocialCategoriasDestroyResponses];

export type SocialCategoriasRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este categoria publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/categorias/{id}/';
};

export type SocialCategoriasRetrieveResponses = {
    200: CategoriaPublicacion;
};

export type SocialCategoriasRetrieveResponse = SocialCategoriasRetrieveResponses[keyof SocialCategoriasRetrieveResponses];

export type SocialCategoriasPartialUpdateData = {
    body?: PatchedCategoriaPublicacionRequest;
    path: {
        /**
         * Un valor de entero único que identifique este categoria publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/categorias/{id}/';
};

export type SocialCategoriasPartialUpdateResponses = {
    200: CategoriaPublicacion;
};

export type SocialCategoriasPartialUpdateResponse = SocialCategoriasPartialUpdateResponses[keyof SocialCategoriasPartialUpdateResponses];

export type SocialCategoriasUpdateData = {
    body: CategoriaPublicacionRequest;
    path: {
        /**
         * Un valor de entero único que identifique este categoria publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/categorias/{id}/';
};

export type SocialCategoriasUpdateResponses = {
    200: CategoriaPublicacion;
};

export type SocialCategoriasUpdateResponse = SocialCategoriasUpdateResponses[keyof SocialCategoriasUpdateResponses];

export type SocialPublicacionesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/social/publicaciones/';
};

export type SocialPublicacionesListResponses = {
    200: Array<PublicacionList>;
};

export type SocialPublicacionesListResponse = SocialPublicacionesListResponses[keyof SocialPublicacionesListResponses];

export type SocialPublicacionesCreateData = {
    body: PublicacionDetailRequestWritable;
    path?: never;
    query?: never;
    url: '/api/social/publicaciones/';
};

export type SocialPublicacionesCreateResponses = {
    201: PublicacionDetail;
};

export type SocialPublicacionesCreateResponse = SocialPublicacionesCreateResponses[keyof SocialPublicacionesCreateResponses];

export type SocialPublicacionesDestroyData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/publicaciones/{id}/';
};

export type SocialPublicacionesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SocialPublicacionesDestroyResponse = SocialPublicacionesDestroyResponses[keyof SocialPublicacionesDestroyResponses];

export type SocialPublicacionesRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/publicaciones/{id}/';
};

export type SocialPublicacionesRetrieveResponses = {
    200: PublicacionDetail;
};

export type SocialPublicacionesRetrieveResponse = SocialPublicacionesRetrieveResponses[keyof SocialPublicacionesRetrieveResponses];

export type SocialPublicacionesPartialUpdateData = {
    body?: PatchedPublicacionDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/publicaciones/{id}/';
};

export type SocialPublicacionesPartialUpdateResponses = {
    200: PublicacionDetail;
};

export type SocialPublicacionesPartialUpdateResponse = SocialPublicacionesPartialUpdateResponses[keyof SocialPublicacionesPartialUpdateResponses];

export type SocialPublicacionesUpdateData = {
    body: PublicacionDetailRequestWritable;
    path: {
        /**
         * Un valor de entero único que identifique este publicacion.
         */
        id: number;
    };
    query?: never;
    url: '/api/social/publicaciones/{id}/';
};

export type SocialPublicacionesUpdateResponses = {
    200: PublicacionDetail;
};

export type SocialPublicacionesUpdateResponse = SocialPublicacionesUpdateResponses[keyof SocialPublicacionesUpdateResponses];

export type SociaslForosListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sociasl/foros/';
};

export type SociaslForosListResponses = {
    200: Array<ForoList>;
};

export type SociaslForosListResponse = SociaslForosListResponses[keyof SociaslForosListResponses];

export type SociaslForosCreateData = {
    body: ForoDetailRequest;
    path?: never;
    query?: never;
    url: '/api/sociasl/foros/';
};

export type SociaslForosCreateResponses = {
    201: ForoDetail;
};

export type SociaslForosCreateResponse = SociaslForosCreateResponses[keyof SociaslForosCreateResponses];

export type SociaslForosDestroyData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este foro.
         */
        id: number;
    };
    query?: never;
    url: '/api/sociasl/foros/{id}/';
};

export type SociaslForosDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SociaslForosDestroyResponse = SociaslForosDestroyResponses[keyof SociaslForosDestroyResponses];

export type SociaslForosRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor de entero único que identifique este foro.
         */
        id: number;
    };
    query?: never;
    url: '/api/sociasl/foros/{id}/';
};

export type SociaslForosRetrieveResponses = {
    200: ForoDetail;
};

export type SociaslForosRetrieveResponse = SociaslForosRetrieveResponses[keyof SociaslForosRetrieveResponses];

export type SociaslForosPartialUpdateData = {
    body?: PatchedForoDetailRequest;
    path: {
        /**
         * Un valor de entero único que identifique este foro.
         */
        id: number;
    };
    query?: never;
    url: '/api/sociasl/foros/{id}/';
};

export type SociaslForosPartialUpdateResponses = {
    200: ForoDetail;
};

export type SociaslForosPartialUpdateResponse = SociaslForosPartialUpdateResponses[keyof SociaslForosPartialUpdateResponses];

export type SociaslForosUpdateData = {
    body: ForoDetailRequest;
    path: {
        /**
         * Un valor de entero único que identifique este foro.
         */
        id: number;
    };
    query?: never;
    url: '/api/sociasl/foros/{id}/';
};

export type SociaslForosUpdateResponses = {
    200: ForoDetail;
};

export type SociaslForosUpdateResponse = SociaslForosUpdateResponses[keyof SociaslForosUpdateResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: UserPublic;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: UserProfile;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];

export type UsersMePartialUpdateData = {
    body?: PatchedUserProfileRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMePartialUpdateResponses = {
    200: UserProfile;
};

export type UsersMePartialUpdateResponse = UsersMePartialUpdateResponses[keyof UsersMePartialUpdateResponses];

export type UsersMeUpdateData = {
    body: UserProfileRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeUpdateResponses = {
    200: UserProfile;
};

export type UsersMeUpdateResponse = UsersMeUpdateResponses[keyof UsersMeUpdateResponses];

export type UsersMeChangePasswordCreateData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/change-password/';
};

export type UsersMeChangePasswordCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersMePetsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/pets/';
};

export type UsersMePetsListResponses = {
    200: Array<Pet>;
};

export type UsersMePetsListResponse = UsersMePetsListResponses[keyof UsersMePetsListResponses];

export type UsersMePetsCreateData = {
    body: PetRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/pets/';
};

export type UsersMePetsCreateResponses = {
    201: Pet;
};

export type UsersMePetsCreateResponse = UsersMePetsCreateResponses[keyof UsersMePetsCreateResponses];

export type UsersMePetsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/me/pets/{id}/';
};

export type UsersMePetsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersMePetsDestroyResponse = UsersMePetsDestroyResponses[keyof UsersMePetsDestroyResponses];

export type UsersMePetsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/me/pets/{id}/';
};

export type UsersMePetsRetrieveResponses = {
    200: Pet;
};

export type UsersMePetsRetrieveResponse = UsersMePetsRetrieveResponses[keyof UsersMePetsRetrieveResponses];

export type UsersMePetsPartialUpdateData = {
    body?: PatchedPetRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/me/pets/{id}/';
};

export type UsersMePetsPartialUpdateResponses = {
    200: Pet;
};

export type UsersMePetsPartialUpdateResponse = UsersMePetsPartialUpdateResponses[keyof UsersMePetsPartialUpdateResponses];

export type UsersMePetsUpdateData = {
    body: PetRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/me/pets/{id}/';
};

export type UsersMePetsUpdateResponses = {
    200: Pet;
};

export type UsersMePetsUpdateResponse = UsersMePetsUpdateResponses[keyof UsersMePetsUpdateResponses];

export type UsersMePetsRestoreCreateData = {
    body: PetRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/me/pets/{id}/restore/';
};

export type UsersMePetsRestoreCreateResponses = {
    200: Pet;
};

export type UsersMePetsRestoreCreateResponse = UsersMePetsRestoreCreateResponses[keyof UsersMePetsRestoreCreateResponses];
